### ISSUE TITLE
Add the LDAP backed realm.

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#44]

**Comment by pedroigor** [comment]
After review the `LdapRealm` configuration options, I would like to discuss if we can simplify it or even change the name of some of the configuration options for *principal mapping*.

* `setDnAttribute`, I think we can remove this option and mark the `setNameAttribute` as required. In this case, whenever the name is in X.500 format or not, we can just execute a search and obtain the DN for specific entry based on the `SearchResult.getNameInNamespace()`.

* `setReloadPrincipalName`, I think we can rename it to `setCachePrincipal(boolean)` instead.

* `setValidatePresence`, do we really need that ? Wondering if `setCachePrincipal(boolean)` is not enough.

* `setNameIsDn`, I think we can rename it to `useX500Name` instead. If I understood it correctly, this attributes tells whether the realm expects usernames as X500 or not. 

* `setPrincipalUseDn`, I think we can rename it to `useX500Principal` instead. If I understood it correctly, this attributes tells whether the realm should return a `X500Principal` or not.

* `setRecursive`, I think a better name would be `useRecursiveSearch` instead.

Also, I think there are some minor improvements we can make to the `LdapSecurityRealm`. For instance, I just noticed that `verifyCredentials` is not working when `setPrincipalUseDn` is `false`. In this case, we need to build the DN first in order to properly authenticate an user.

**Comment by pedroigor** [comment]
Here is an example about how the config looks like so far:

```
<ldap-realm name="LdapRealm">
            <dir-context url="ldap://localhost:11390/" principal="uid=server,dc=elytron,dc=wildfly,dc=org" credential="serverPassword"/>
            <principal-mapping cache-principal="false" name-attribute="uid" use-x500-name="false" use-x500-principal="true" use-recursive-search="true" search-base-dn="dc=elytron,dc=wildfly,dc=org"/>
</ldap-realm>
```
